# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-11 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20180604_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('likes', models.ManyToManyField(related_name='likers', to='marketplace.UserProfileInfo')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='marketplace.UserProfileInfo')),
            ],
            options={
                'verbose_name_plural': 'statuses',
            },
        ),
    ]
