# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-13 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
