AWS_UPLOAD_BUCKET = "aixai-datasets"

AWS_UPLOAD_USERNAME = "sajid"

AWS_UPLOAD_GROUP = "admins"

AWS_UPLOAD_REGION = 'us-west-2'

AWS_UPLOAD_ACCESS_KEY_ID = "AKIAIEUOUQILWY6KSRTQ"

AWS_UPLOAD_SECRET_KEY = "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"
